pipeline:
  identify:
    image: alpine
    commands:
      - apk add --no-cache curl jq
      - set -o pipefail
      - curl -fL https://api.github.com/repos/cardigann/cardigann/releases/latest
          | jq -r .tag_name
          | tr -d 'v'
          | tee /dev/stderr > .cardigann_tag

  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: cardigann-dev
    build_args:
      - 'CARDIGANN_VER=%file: .cardigann_tag'

  test:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - apk add --no-cache curl
      - CON_NAME=$(docker run -dt -e SUID=0 cardigann-dev)
      - timeout -t 8 -- docker logs -f $$CON_NAME | cat &
      - sleep 5
      - IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $$CON_NAME)
      - if [ -z "$IP" ]; then
            echo "The container exited.. sadpanda";
            docker inspect --format='{{.State.ExitCode}}' $$CON_NAME;
            docker rm $$CON_NAME
            exit 25;
        fi
      - curl -L --retry-max-time 30 --max-time 5 --retry 10 --retry-delay 5 --retry-connrefused $IP:5060 > /dev/null
      - docker kill $$CON_NAME
      - docker rm $$CON_NAME

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    from: cardigann-dev
    repo: spritsail/cardigann
    tags:
      - 'latest'
      - '%fileauto: .cardigann_tag'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
