pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: cardigann-dev

  test:
    image: spritsail/docker-test
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: cardigann-dev
    run_args: -e SUID=0
    curl: ':5060'

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    from: cardigann-dev
    repo: spritsail/cardigann
    tags:
      - 'latest'
      - '%label io.spritsail.version.cardigann | %auto'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
